[package]
name = "rsbar"
version = "1.0.4"
edition = "2021"

[dependencies]
async-trait = "0.1.82"
gtk4 = { version = "0.8.2", features = ["v4_12"] }
gtk4-layer-shell = "0.3.0"
once_cell = "1.19.0"
tokio = { version = "1.38.0", features = ["full"] }
log = "0.4.22"
colog = "1.3.0"
