[package]
name = "rsbar-tester"
version = "0.0.1"
edition = "2021"

[dependencies]
rayon = "1.10"
tokio = { version = "1.38.0", features = ["full"] }
serde = {version="1.0.203", features=["derive"]}
serde_json = "1.0.118"
