[package]
name = "rsbar-daemon"
version = "0.0.1"
edition = "2021"

[dependencies]
chrono = "0.4.38"
once_cell = "1.19.0"
async-trait = "0.1.82"
tokio = { version = "1.38.0", features = ["full"] }
serde = {version="1.0.203", features=["derive"]}
serde_json = "1.0.118"
